sudo: false
language: node_js
node_js:
  - "12"
branches:
  only:
    - develop
    - master
    - ROUT-44-continuous-integration
git:
  submodules: false
cache:
  directories:
    - node_modules
before_script:
  - ./install.sh
jobs:
  include:
    - stage: "build"
      name: "Building services"
      script: ./build.sh
