language: node_js
os:
  - 'linux'
node_js:
  - '12'
branches:
  only:
  - '/.*/'
services:
    - docker
cache:
  directories:
  - node_modules
script:
  - npm run test
  - bash <(curl -s https://codecov.io/bash)