version: '2'
services:
  # dns:
  #   container_name: dns-lookup
  #   build:
  #     context: .
  #     dockerfile: dns-lookup/Dockerfile
  #   environment:
  #     - PORT=5000
  #   ports:
  #     - '80:5000'
  msg_broker:
    container_name: msg_broker
    build:
      context: .
      dockerfile: msg_broker/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
  #   depends_on:
  #     - rabbitmq
  # rabbitmq:
  #   container_name: rabbitmq
  #   image: rabbitmq:3.7-management
  #   environment:
  #     - RABBITMQ_ERLANG_COOKIE=secret
  #   ports:
  #     - '15672:15672'
  #     - '5672'
  # pcap:
  #   container_name: pcap
  #   build:
  #     context: .
  #     dockerfile: pcap/Dockerfile
  #   network_mode: 'host'
  #   environment:
  #     - RABBITMQ_URL=amqp://127.0.0.1:5672
  #   depends_on:
  #    - rabbitmq
  dhcp:
    container_name: dhcp
    build:
      context: .
      dockerfile: dhcp/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://127.0.0.1:5672
    network_mode: 'host'
    ports:
      - '67:67'
      - '4000:4000'
    # depends_on:
    #  - rabbitmq
