version: '2'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management
    environment:
        RABBITMQ_ERLANG_COOKIE: 'secret'
        # RABBITMQ_DEFAULT_USER: vivi
        # RABBITMQ_DEFAULT_PASS: 'vivitek'
    ports:
        - '15672:15672'
        - '5672:5672'
  msg_broker:
    container_name: msg_broker
    image: node:lts
    volumes: 
      - './msg_broker:/app'
    working_dir: '/app'
    command: 'yarn start'
    depends_on:
      - rabbitmq
    environment: 
      BALENA_DEVICE_UUID: d8b8d93ada292a53d3c659a944ef4106
      RABBITMQ_URL: amqp://rabbitmq
  pcap:
    container_name: pcap
    build:
      context: .
      dockerfile: pcap/DockerfileDev
    environment:
      RABBITMQ_URL: amqp://localhost:5672
    network_mode: host
    depends_on:
      - rabbitmq
  dhcp:
    container_name: dhcp
    image: node:lts
    volumes:
      - './dhcp/built:/app/dhcp'
      - './dhcp/node_modules:/app/dhcp/node_modules'
    working_dir: '/app/dhcp'
    command: 'node dhcp/src/index.js'
    depends_on:
     - rabbitmq
