version: '2'
services:
  dns:
    container_name: dns-lookup
    image: node:lts
    ports:
      - '4000:3000'
    volumes:
      - './dns-lookup:/app'
    working_dir: '/app'
    command: 'yarn dev'
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management
    environment:
        RABBITMQ_ERLANG_COOKIE: 'secret'
        # RABBITMQ_DEFAULT_USER: vivi
        # RABBITMQ_DEFAULT_PASS: 'vivitek'
    ports:
        - '15672:15672'
        - '5672:5672'
  msg_broker:
    container_name: msg_broker
    image: node:lts
    volumes: 
      - './msg_broker:/app'
    working_dir: '/app'
    command: 'yarn start'
    depends_on:
      - rabbitmq
    environment: 
      RABBITMQ_URL: amqp://rabbitmq
  agent:
    container_name: agent
    image: node:lts
    working_dir: /app
    volumes:
      - './agent:/app'
    command: 'yarn start'
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://rabbitmq
  pcap:
    container_name: pcap
    image: node:lts
    volumes:
      - './pcap:/app'
    command: 'yarn start'
    working_dir: /app
    depends_on: 
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq
  dhcp:
    container_name: dhcp
    image: node:lts
    volumes:
      - './dhcp:/app/dhcp'
      - './dhcp:/app/utils'
    working_dir: '/app/dhcp'
    command: 'node src/index.js'
    depends_on:
     - rabbitmq
