version: '3.7'
services:
    dhcp:
        container_name: dhcp
        build: ./dhcp
        ports:
            - '67:67'
        networks: 
            - 'test'
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.7-management
        environment: 
            RABBITMQ_ERLANG_COOKIE: 'secret'
            # RABBITMQ_DEFAULT_USER: vivi
            # RABBITMQ_DEFAULT_PASS: 'vivitek'
        ports:
            - '15672:15672'
            - '5672:5672'
        networks:
            - 'test'
    sender:
        container_name: sender
        build: ./pcap
        networks:
            - 'test'
        depends_on: 
            - rabbitmq
        environment: 
            RABBITMQ_URL: amqp://rabbitmq
    receiver:
        container_name: receiver
        build: ./msg_broker
        networks:
            - 'test'
        depends_on: 
            - rabbitmq
        environment: 
            RABBITMQ_URL: amqp://rabbitmq
networks:
    test: