version: '3.7'
services:
    dhcp:
        container_name: dhcp
        build: ./dhcp
        ports:
            - '67:67'
        depends_on:
            - 'rabbitmq'
        environment:
            RABBITMQ_URL: amqp://rabbitmq
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.7-management
        environment: 
            RABBITMQ_ERLANG_COOKIE: 'secret'
            # RABBITMQ_DEFAULT_USER: vivi
            # RABBITMQ_DEFAULT_PASS: 'vivitek'
        ports:
            - '15672:15672'
            - '5672:5672'
    pcap:
        container_name: pcap
        build: ./pcap
        depends_on: 
            - rabbitmq
        ports:
            - '5000:5000'
        network_mode: 'host'
        environment: 
            RABBITMQ_URL: amqp://127.0.0.1:5672
    msg_broker:
        container_name: msg_broker
        build: ./msg_broker
        depends_on: 
            - rabbitmq
        environment: 
            RABBITMQ_URL: amqp://rabbitmq