FROM balenalib/%%BALENA_MACHINE_NAME%%-node
WORKDIR /app
RUN install_packages libpcap-dev python3 build-essential
COPY package.json .
RUN npm install
RUN npm install typescript -g 
COPY . .
RUN tsc
CMD ["node", "dist/index.js"]
