FROM balenalib/%%BALENA_MACHINE_NAME%%-python

COPY . .
ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
RUN install_packages python3-dbus
RUN pip install uuid
CMD [ "python3.7", "app.py" ]