# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Balena-CLI Builds

on:
  push:
    branches: [develop, ci]
  pull_request:
    branches: [develop]

jobs:
  build_rpi_4:
    runs-on: ["ubuntu-latest"]
    user: "root"

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: wget https://github.com/balena-io/balena-cli/releases/download/v12.44.14/balena-cli-v12.44.14-linux-x64-standalone.zip
      - run: unzip balena-cli-v12.44.14-linux-x64-standalone.zip
      - run: mkdir -p /home/travis/.balena/bin
      - run: chmod -R 777 /home/travis/.balena
      - run: export PATH=$PATH:$PWD/balena-cli && ./build_rpi4.sh
  build_rpi_3:
    runs-on: ["ubuntu-latest"]
    user: "root"

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: wget https://github.com/balena-io/balena-cli/releases/download/v12.44.14/balena-cli-v12.44.14-linux-x64-standalone.zip
      - run: unzip balena-cli-v12.44.14-linux-x64-standalone.zip
      - run: mkdir -p /home/travis/.balena/bin
      - run: chmod -R 777 /home/travis/.balena
      - run: export PATH=$PATH:$PWD/balena-cli && ./build_rpi3.sh
